### ISSUE TITLE
Decoding Error on malformed domain name

### ISSUE THREAD

**Issue by ArneTR** [DaveRandom/LibDNS#7] opened 2016-04-24 14:04 UTC
When trying to dns-check the domain "web.e" I get 

Empty domain name at position 0x17

Tested on Google-DNS 8.8.8.8 which, for a dig command, returns, 

; <<>> DiG 9.8.3-P1 <<>> web.e A @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 59673
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 0

;; QUESTION SECTION:
;web.e.             IN  A

;; AUTHORITY SECTION:
.           702 IN  SOA a.root-servers.net. nstld.verisign-grs.com. 2016042400 1800 900 604800 86400

;; Query time: 26 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Apr 24 16:04:25 2016
;; MSG SIZE  rcvd: 98

**Comment by DaveRandom** [comment] 2016-04-29 20:56
Probably a dupe of #6 but I'll leave this open for now in case it isn't - this repo needs some love in general, I've neglected it for too long. I'll try and get to this in the next week or two, but PRs are welcome :-)

**Comment by ArneTR** [comment] 2016-09-18 18:26
I fixed the problem in the version I am using here @home. However, I do not fully understand why the problem happens.

I investigated the problem to a certain extent and will try to outline what I know so far:

It most like is a dupe of #6 as the problem is in the function **decodeDomainName** of **/src/Decoder/Decoder.php**

## decodeDomainName

The while loop expects packets with data in them. When a zero-length packet occurs the whole loop is not processed leading to the **UnexpectedValueException**
A zero-length packet may occur on a non-existent TLD-record. For example **google.c**
As I understand it this is protocol works by specifying the incoming length through a byte-sized field ... followed by the content.
Since the length here is 0, this seems to lead to unexpected behaviour.

The authority section will be empty, which can also be checked with **dig** This is currently not handled correctly.

### dig call of google.c
```bash
$ dig google.c A @8.8.8.8

; <<>> DiG 9.10.3-P4-Ubuntu <<>> google.c A @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 37969
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;google.c.			IN	A

;; AUTHORITY SECTION:
.			1797	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2016091800 1800 900 604800 86400

;; Query time: 55 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Sun Sep 18 20:16:55 CEST 2016
;; MSG SIZE  rcvd: 112
```
> _dig displays a **.** but in reality the packet has zero-length according what I could see in the hexdump_

My patch is the following part of code right after the while loop on line [237](https://github.com/DaveRandom/LibDNS/blob/master/src/Decoder/Decoder.php#L237)

```php
if($initial_package_length - $packet->getBytesRemaining() === 1) {
  throw new ZeroSizeFieldException('Zero size field detected ... probably tld without authority');                 }
```
Currently I do catch this Exception and handle accordingly. However, a proper fixing of the loop seems to be the better solution here.

The exception bubbles up to the parent frame of the function **decodeResourceRecord**

Here, decodeDomainName has two occurences. Once directly on line [414](https://github.com/DaveRandom/LibDNS/blob/master/src/Decoder/Decoder.php#L414), and once inside of **decodeType** on line [428](https://github.com/DaveRandom/LibDNS/blob/master/src/Decoder/Decoder.php#L428)

My patch here is to catch **ZeroSizeFieldException** at both occurences, but handle it differently. In the former case I trigger another Exception, cause at this point it is clear that we encountered a non-existent TLD.
In the latter case I just advance the cursor by decrementing the remaining length, as the packet was not properly consumed in the broken while loop.


### Complete patched function decodeResourceRecord()
```php
    private function decodeResourceRecord(DecodingContext $decodingContext)
    {
        /** @var \LibDNS\Records\Types\DomainName $domainName */
        $domainName = $this->typeBuilder->build(Types::DOMAIN_NAME);
        try {
          $this->decodeDomainName($decodingContext, $domainName);
        } catch (ZeroSizeFieldException $e) {
            throw new NonexistentTLDException();
        }

        $meta = unpack('ntype/nclass/Nttl/nlength', $this->readDataFromPacket($decodingContext->getPacket(), 10));

        $resource = $this->resourceBuilder->build($meta['type']);
        $resource->setName($domainName);
        $resource->setClass($meta['class']);
        $resource->setTTL($meta['ttl']);

        $data = $resource->getData();
        $remainingLength = $meta['length'];

        $fieldDef = $index = null;
        foreach ($resource->getData()->getTypeDefinition() as $index => $fieldDef) {
            $field = $this->typeBuilder->build($fieldDef->getType());
            try {
              $remainingLength -= $this->decodeType($decodingContext, $field, $remainingLength);
              $data->setField($index, $field);
            } catch (ZeroSizeFieldException $e) {
                $remainingLength -=1;
            }
        }

        if ($fieldDef->allowsMultiple()) {
            while ($remainingLength) {
                $field = $this->typeBuilder->build($fieldDef->getType());
                $remainingLength -= $this->decodeType($decodingContext, $field, $remainingLength);
                $data->setField(++$index, $field);
            }
        }

        if ($remainingLength !== 0) {
            throw new \UnexpectedValueException('Decode error: Invalid length for record data section');
        }

        return $resource;
    }
```


### Summary

This sums up the problems I encountered while checking multiple hundred domains daily with this function, this patch _works_, but is far from good :).

Following anomalies trigger this error:
- Non-Existent TLD ... leading to missing authority section _Example: google.c_
- Non-Existent A/MX Record, leading to missing answer section _Example: jaoo.com_

**Comment by DaveRandom** [comment] 2018-01-28 13:31
Fixed in master (v3)

**Closed by DaveRandom** 2018-01-28 13:31 UTC
